import Head from 'next/head'
import React from 'react'
import ProjectCard from '../Components/Cards/ProjectCard'
import { Project } from '../Helper/Data'

function Projects() {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='grid gap-2 px-4 text-white lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1'>
      {
        Project.map((i)=>(
          <ProjectCard title={i.title} description={i.description} information={i.infomation} techstack={i.techstack}/>
          )) 
        }  
     <div className='col-auto lg:col-span-3 '>
      <p>
      * Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum, ad.
      </p>
      <p> 
      * Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, quam.
      </p>
        </div>
     </div>
    </div>
  )
}

export default Projects