import Head from 'next/head'
import React from 'react'
import EducationCard from '../Components/Cards/EducationCard'
import ExperienceCard from '../Components/Cards/ExperienceCard'
import { CondingSkills, Education, Experience } from '../Helper/Data'

function skills() {
  return (
    <div>
    <Head>
      <title>NextJS Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='grid grid-cols-1 gap-10 px-6 lg:grid-cols-2 sm:grid-cols-1'>
      <div className='rounded-xl'>
        <div className='py-4'>
        <h3 className='py-4 text-3xl font-bold text-indigo-300'>Coding Skills</h3>
        <div className='py-2 my-4 text-white bg-black rounded-xl '>
        <div>
         <ul className='grid grid-cols-3 font-bold'>
           {
             CondingSkills.map((i)=>(
               <li className='m-auto'>{i.skillname}</li>
             ))
           }
         </ul>
        </div>
      </div>
          <h3 className='py-2 text-3xl font-bold text-indigo-300'>Education</h3>
          {
            Education.map((i)=>(
          <EducationCard education={i.education} grade={i.education} organization={i.organization} sub={i.sub} year={i.year} />              
            ))
          }    
        </div>
      </div>
      <div className='my-4 rounded-xl'>
        <div className=''>
          <h3 className='py-4 text-3xl font-bold text-indigo-300'>Experience</h3>
          {
            Experience.map((i)=>(          
           <ExperienceCard Organization={i.organization} responsibilty={i.responsibilty} year={i.year} designation={i.designation} />
            ))
          }
        </div>
      </div>
     </div>
    </div>
  )
}

export default skills